openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: 노트 관리 API

paths:
  /notes:
    get:
      summary: 모든 노트 조회
      responses:
        "200":
          description: 노트 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
    post:
      summary: 새 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteInput"
      responses:
        "201":
          description: 생성된 노트 반환
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"

  /notes/{id}:
    get:
      summary: 특정 노트 조회
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 노트 반환
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "404":
          description: 노트를 찾을 수 없음
    put:
      summary: 노트 수정
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteInput"
      responses:
        "200":
          description: 수정된 노트 반환
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "404":
          description: 노트를 찾을 수 없음
    delete:
      summary: 노트 삭제
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: 삭제 성공
        "404":
          description: 노트를 찾을 수 없음

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    NoteInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
